# Generated by Django 3.2.16 on 2022-11-16 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worklow', to='recruiter.job')),
            ],
        ),
        migrations.CreateModel(
            name='Stepper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step', to='workflow.workflow')),
            ],
        ),
    ]
