# Generated by Django 3.2.16 on 2022-11-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('recruiter', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_types',
            field=models.ManyToManyField(blank=True, null=True, to='tag.JobTag'),
        ),
    ]
