# Generated by Django 3.2.16 on 2022-11-17 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0004_stepper_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklows', to='recruiter.job'),
        ),
    ]
