# Generated by Django 3.2.16 on 2022-11-19 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0005_alter_workflow_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='recruiter.job'),
        ),
    ]
