# Generated by Django 3.2.16 on 2022-11-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtag',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='programminglanguagetag',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
